---
{{- if .Values.twemproxy.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "twemproxy" . }}
  labels:
    app: {{ template "twemproxy" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    {{- toYaml .Values.twemproxy.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.twemproxy.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "twemproxy" . }}
      annotations:
      {{- toYaml .Values.twemproxy.annotations | nindent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - image: jcbarrales/redis_exporter
          imagePullPolicy: Always
          name: redis-exporter
          ports:
          - containerPort: {{ .Values.twemproxy.exporter.port }}
            protocol: TCP
          resources: 
          {{- toYaml .Values.twemproxy.exporter.resources | nindent 12 }}
        - name: {{ template "twemproxy" . }}
          image: {{ .Values.twemproxy.image }}
          ports:
          - containerPort: 6379
          livenessProbe:
          {{- toYaml .Values.twemproxy.livenessProbe | nindent 12 }}
          readinessProbe:
          {{- toYaml .Values.twemproxy.readinessProbe | nindent 12 }}     
          resources: 
          {{- toYaml .Values.twemproxy.resources | nindent 12 }}
          env:
            - name: "SERVERS"
              value: "{{- $root := . -}}{{ template "fullname" $root }}-0:6379:1{{- range $i, $e := until ( sub ( .Values.redis.replicaCount | int) 1 | int ) }},{{ template "fullname" $root }}-{{ add $e 1 }}:6379:1{{- end -}}"
---
 {{ end }}